services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file: 
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7
    ports: 
      - "6380:6379"
  postgres:
    image: postgres:15
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kavachdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
